-- S3: Household invite codes
-- Each row is a single-use, 24-hour invite code generated by a household owner.
-- The code field is the joinable token; householdId is only resolved server-side.
CREATE TABLE "household_invites" (
    "id"           TEXT        NOT NULL,
    "household_id" TEXT        NOT NULL,
    "code"         TEXT        NOT NULL,
    "created_by"   TEXT        NOT NULL,
    "expires_at"   TIMESTAMPTZ NOT NULL,
    "used_at"      TIMESTAMPTZ,
    "used_by"      TEXT,

    CONSTRAINT "household_invites_pkey" PRIMARY KEY ("id")
);

-- Unique constraint: each code must be globally unique so a code cannot be
-- redirected to a different household by collision.
CREATE UNIQUE INDEX "household_invites_code_key" ON "household_invites"("code");

-- Index for rate-limit query: "how many active codes does this household have?"
CREATE INDEX "household_invites_household_id_idx" ON "household_invites"("household_id");

-- Index for redemption lookup: find invite by code in O(log n).
CREATE INDEX "household_invites_code_idx" ON "household_invites"("code");
